version: '3.2'

services:
    database:
        container_name: hacker-gif-poll-database
        image: hacker-gif-poll-database-image
        build:
            context: ./src/database
            dockerfile: ./docker/Dockerfile
            args:
                - TZ=America/Sao_Paulo
        env_file:
            - ./src/database/docker/.database.env
        volumes:
            - type: volume
              source: hacker-gif-poll-database-data
              target: /var/lib/postgresql/pgdata
        ports:
            - target: 5432
              published: 5432
        networks:
            - hacker-gif-poll-network

    backend:
        container_name: hacker-gif-poll-backend
        command: ../wait-for.sh database:5432 -- python3 manage.py runserver 0.0.0.0:8000
        image: hacker-gif-poll-backend-image
        user: root
        build:
            context: ./src/backend
            dockerfile: ./docker/Dockerfile
            args:
                - TZ=America/Sao_Paulo
        volumes:
            - type: bind
              source: ./src/backend/hacker_gif_poll
              target: /hacker_gif_poll/backend
        env_file:
            - ./src/backend/docker/.backend.env
        ports:
            - target: 8000
              published: 8000
        depends_on:
            - database
        networks:
            - hacker-gif-poll-network

    frontend:
        container_name: hacker-gif-poll-frontend
        image: hacker-gif-poll-frontend-image
        user: root
        # stdin_open added due to a bug in reacts-scripts@^3.4.0
        # issue: https://github.com/git-insights/git-insights/issues/24
        stdin_open: true 
        build:
            context: ./src/frontend
            dockerfile: ./docker/Dockerfile
            args:
                - TZ=America/Sao_Paulo
        env_file:
            - ./src/frontend/docker/.frontend.env
        volumes:
            - type: bind
              source: ./src/frontend/hacker_gif_poll/public
              target: /hacker_gif_poll/frontend/public
            - type: bind
              source: ./src/frontend/hacker_gif_poll/src
              target: /hacker_gif_poll/frontend/src
            - type: bind
              source: ./src/frontend/hacker_gif_poll/schema.json
              target: /hacker_gif_poll/frontend/schema.json
        ports:
            - target: 3000
              published: 3000
        depends_on:
            - backend
        networks:
            - hacker-gif-poll-network

volumes:
    hacker-gif-poll-database-data:

networks:
    hacker-gif-poll-network:
