strictness: veryhigh
test-warnings: true
doc-warnings: false
max-line-length: 120

uses:
    - django

ignore-paths:
    - app

pylint:  
    disable:
        - bad-builtin
        - too-few-public-methods
        - import-error
        - unused-argument
        - broad-except
        - missing-docstring
        - star-args
    options:
        good-names: pk,urlpatterns
          
pep8:
    full: true
    disable:
        - E126
          
pep257:
    disable:
        - D100
        - D101
        - D102
        - D103
        - D205
        - D400
        - D401
